/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package su.weblock.schema.extrapolator;

import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;

import su.weblock.schema.common.exception.SEBaseException;
import su.weblock.schema.openapi.OpenApi3CompatibleSchema;
import su.weblock.schema.openapi.exception.IncompatibleWithOpenApiSchema;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

    String makeJsonStr(OpenApi3CompatibleSchema schema) throws JsonProcessingException{
        var om = new ObjectMapper();
        om.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        om.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);
        om.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
        return om.writerWithDefaultPrettyPrinter().writeValueAsString(schema);
    }

    @Test     
    public void urlencodedTest1() throws SEBaseException, JsonProcessingException {
        var extr = ExtrapolatorMaker.make("application/x-www-form-urlencoded");        
        assertNotNull(extr);

        
        assert(extr.pushSample("xxx=1&t=7".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx=3&y=efw32fde".getBytes())== Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx=67&t=9".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx=1&y=24sdfdf7".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("y=uiii&d=22345200-abe8-4f60-90c8-0d43c5f6c0f6".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx=8&lol2=24".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx=68&lol2=67".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx=68&lol3=qwert1".getBytes())== Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx=68&lol2=qwe3333".getBytes())== Extrapolator.SampleParsingResult.SUCCESS);        
        assertNotNull(extr.result().getShortStringDescription(), "URLENCODED TEST1: failed");

        System.out.println(extr.result().getShortStringDescription());
        
        var oa3_schema = extr.result().getOpenApiCompatibleSchema();
        assert(oa3_schema.type.equals("object"));
        assert(oa3_schema.properties.get("lol2").type.equals("string"));
        assert(oa3_schema.properties.get("d").type.equals("string"));
        assert(oa3_schema.properties.get("d").format.equals("uuid"));

        var om = new ObjectMapper();
        om.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        om.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);
        om.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
        var json_str = om.writerWithDefaultPrettyPrinter().writeValueAsString(oa3_schema);
        System.out.println("JSON:");
        System.out.println(json_str);
        
        var tree = om.readTree(json_str);
        assert(tree.get("properties").get("lol2").get("type").asText().equals("string"));        
        assert(tree.get("properties").get("t").get("type").asText().equals("integer"));        
        assert(tree.get("properties").get("xxx").get("type").asText().equals("integer"));  
    }

    @Test
    public void urlencodedTest2() throws SEBaseException, JsonMappingException, JsonProcessingException {
        var extr = ExtrapolatorMaker.make("application/x-www-form-urlencoded");        
        assertNotNull(extr);
        
        assert(extr.pushSample("xxx12=1&aab22=7".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx12=1&token".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx12=0&qwert=yes".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);        
        assert(extr.pushSample("xxx12=1&qwert=no".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);           
        assert(extr.pushSample("num=1.67&aab22=90".getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);               

        var schema = extr.result().getShortStringDescription();
        assertNotNull(schema, "URLENCODED TEST1: failed");

         
        var om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);

        assert(tree.get("xxx12").asText().equals("BOOLEAN"));        
        assert(tree.get("qwert").asText().equals("BOOLEAN_STR"));   
        assert(tree.get("num").asText().equals("FLOAT"));

        System.out.println(schema);         
        assertThrowsExactly(IncompatibleWithOpenApiSchema.class, () -> extr.result().getOpenApiCompatibleSchema());
    }   
    
    @Test     
    public void multipartTest1() throws SEBaseException, JsonMappingException, JsonProcessingException {    
        var extr = ExtrapolatorMaker.make("multipart/form-data"); 
        String multipart_body1 =
            "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=\"string_param1-name\"\r\n"
            + "\r\n"
            + "Larry\r\n"
            + "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=string_param2-name\r\n"
            + "\r\n"
            + "Larry2222\r\n"
            + "----AaB03x\r\n"            
            + "Content-Disposition: form-data; name=\"files\"; filename=\"file1.txt\"\r\n"
            + "Content-Type: text/plain\r\n"
            + "\r\n"
            + "HELLO WORLD!\r\n"
            + "----AaB03x--\r\n";

        assert(extr.pushSample(multipart_body1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 

        String multipart_body2 =
            "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=\"string_param4-name\"\r\n"
            + "\r\n"
            + "Larry\r\n"
            + "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=string_param3-name\r\n"
            + "\r\n"
            + "Larry2222\r\n"
            + "----AaB03x\r\n"            
            + "Content-Disposition: form-data; name=\"files1\"; filename=\"file1.txt\"\r\n"
            + "Content-Type: text/plain\r\n"
            + "\r\n"
            + "HELLO WORLD!\r\n"
            + "----AaB03x--\r\n";

        assert(extr.pushSample(multipart_body2.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);         
        
        var schema = extr.result().getShortStringDescription();
        assertNotNull(schema, "MULTIPART TEST1: failed");
          
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);

        assert(tree.get("files1").asText().equals("FILE"));        
        assert(tree.get("string_param3-name").asText().equals("STRING"));

        System.out.println(schema);    
        
        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("properties").get("string_param3-name").get("type").asText().equals("string"));        
        assert(tree.get("properties").get("string_param4-name").get("type").asText().equals("string"));        
        assert(tree.get("properties").get("files1").get("type").asText().equals("string"));          
        assert(tree.get("properties").get("files1").get("format").asText().equals("binary"));  
    }

    @Test     
    public void multipartTest2() throws SEBaseException, JsonProcessingException {    
        var extr = ExtrapolatorMaker.make("multipart/form-data"); 
        String multipart_body1 =
            "----AaB03x\r\n"
            + "Content-Disposition: form-data; name1=\"string_param1-name\"\r\n"
            + "\r\n"
            + "Larry\r\n"
            + "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=string_param2-name\r\n"
            + "\r\n"
            + "Larry2222\r\n"
            + "----AaB03x\r\n"            
            + "Content-Disposition: form-data; name=\"files\"; filename=\"file1.txt\"\r\n"
            + "Content-Type: text/plain\r\n"
            + "\r\n"
            + "HELLO WORLD!\r\n"
            + "----AaB03x--\r\n";

        assert(extr.pushSample(multipart_body1.getBytes()) == Extrapolator.SampleParsingResult.ERROR); 

        assertNotNull(extr.result().getShortStringDescription(), "MULTIPART TEST2: failed");

        System.out.println(extr.result().getShortStringDescription());                 
    }

    @Test     
    public void multipartTest3() throws SEBaseException, JsonProcessingException {    
        var extr = ExtrapolatorMaker.make("multipart/form-data"); 
        String multipart_body1 =
            "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=\"string_param1-name\"\r\n"
            + "\r\n"
            + "Larry\r\n"
            + "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=string_param2-name\r\n"
            + "\r\n"
            + "Larry2222\r\n"
            + "----AaB03x\r\n"            
            + "Content-Disposition: form-data; name=\"files\"; filename=\"file1.txt\"\r\n"
            + "Content-Type: text/plain\r\n"
            + "\r\n"
            + "HELLO WORLD!\r\n"
            + "----AaB03x--\r\n";

        assert(extr.pushSample(multipart_body1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 

        String multipart_body2 =
            "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=\"files\"\r\n"
            + "\r\n"
            + "Larry\r\n"
            + "----AaB03x\r\n"
            + "Content-Disposition: form-data; name=string_param3-name\r\n"
            + "\r\n"
            + "Larry2222\r\n"
            + "----AaB03x\r\n"            
            + "Content-Disposition: form-data; name=\"files1\"; filename=\"file1.txt\"\r\n"
            + "Content-Type: text/plain\r\n"
            + "\r\n"
            + "HELLO WORLD!\r\n"
            + "----AaB03x--\r\n";

        assert(extr.pushSample(multipart_body2.getBytes()) == Extrapolator.SampleParsingResult.INCOMPATIBLE);

        assertNotNull(extr.result().getShortStringDescription(), "MULTIPART TEST3: failed");

        System.out.println(extr.result().getShortStringDescription());  
        
        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        var tree = omj.readTree(json_str);
        assert(tree.get("properties").get("string_param1-name").get("type").asText().equals("string"));                     
        assert(tree.get("properties").get("files").get("type").asText().equals("string"));          
        assert(tree.get("properties").get("files").get("format").asText().equals("binary"));             
    }    

    @Test     
    public void jsonTest1() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/json"); 
        String json1 = "{\"xx\":1}";
        assert(extr.pushSample(json1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String json2 = "{\"yy\":\"qwert\"}";
        assert(extr.pushSample(json2.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);  
        String json3 = "{\"zz\":[1,2,3,4,5]}";
        assert(extr.pushSample(json3.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String json4 = "{\"zz\":[1,2,\"lol1\", \"lol2\"]}";
        assert(extr.pushSample(json4.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String json5 = "{\"aa\":{\"lol5\": true}}";
        assert(extr.pushSample(json5.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String json6 = "{\"aa\":{\"lol6\": \"loadasd\"}}";
        assert(extr.pushSample(json6.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String json7 = "{\"zz\":[6, {\"qwer\":\"dddffff\"}, 8]}";
        assert(extr.pushSample(json7.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String json8 = "{\"aa\":null}";
        assert(extr.pushSample(json8.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        var schema = extr.result().getShortStringDescription();

        String json9 = "{\"xx\":\"qwert\"}";
        assert(extr.pushSample(json9.getBytes()) == Extrapolator.SampleParsingResult.INCOMPATIBLE);  
        String json10 = "{\"xx\":\"qwert}";
        assert(extr.pushSample(json10.getBytes()) == Extrapolator.SampleParsingResult.ERROR);           

        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);

        assert(tree.get("xx").asText().equals("INTEGER"));
        assert(tree.get("aa").get("lol5").asText().equals("BOOLEAN"));
        assert(tree.get("yy").asText().equals("STRING"));

        System.out.println(schema);

        assertThrowsExactly(IncompatibleWithOpenApiSchema.class, () -> extr.result().getOpenApiCompatibleSchema());    
    }
    
    @Test     
    public void jsonTest2() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/json"); 
        String json1 = "{\"xx\":1}";
        assert(extr.pushSample(json1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String json2 = "{\"xx\":\"qwert\"}";
        assert(extr.pushSample(json2.getBytes()) == Extrapolator.SampleParsingResult.INCOMPATIBLE);  
        String json3 = "{\"xx\":\"qwert}";
        assert(extr.pushSample(json3.getBytes()) == Extrapolator.SampleParsingResult.ERROR);         

        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);

        assert(tree.get("xx").asText().equals("INTEGER"));

        System.out.println(schema);


        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("properties").get("xx").get("type").asText().equals("integer"));
    }

    @Test     
    public void jsonTest3() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/json"); 
        String json1 = "{\"xx\":[]}";
        assert(extr.pushSample(json1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);         

        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);   
        assert(tree.get("xx").iterator().next().asText().equals("null"));     

        System.out.println(schema);        
    }
    
    @Test     
    public void jsonTest4() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/json"); 
        String json1 = "{\"xx\":[6,7]}";
        assert(extr.pushSample(json1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);         

        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);   

        System.out.println(schema);
        var iter = tree.get("xx").iterator();
        assert(iter.next().asText().equals("INTEGER"));     
        assert(!iter.hasNext());        

        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("properties").get("xx").get("type").asText().equals("array"));        
        assert(tree.get("properties").get("xx").get("items").get("type").asText().equals("integer"));        
    }

    @Test     
    public void jsonTest5() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/json"); 
        String json1 = "[6,7]";
        assert(extr.pushSample(json1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);         

        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);   

        System.out.println(schema);
        var iter = tree.iterator();
        assert(iter.next().asText().equals("INTEGER"));     
        assert(!iter.hasNext());  
        
        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("type").asText().equals("array"));                
        assert(tree.get("items").get("type").asText().equals("integer"));    
    }

    @Test     
    public void jsonTest6() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/json"); 
        String json1 = "true";
        assert(extr.pushSample(json1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);
        String json2 = "45";        
        assert(extr.pushSample(json2.getBytes()) == Extrapolator.SampleParsingResult.INCOMPATIBLE);
        String json3 = "fs45";
        assert(extr.pushSample(json3.getBytes()) == Extrapolator.SampleParsingResult.ERROR);

        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);   

        System.out.println(schema);
        assert(tree.asText().equals("BOOLEAN"));

        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("type").asText().equals("boolean"));                
    } 
    

    @Test     
    public void jsonTest7() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/json"); 
        String json1 = "{\"arrayW1\":[1,2,3],\"boolean\":true,\"color\":\"gold\",\"null\":null,\"numberTest\":123,\"floatTest\":123.6,\"object\":{\"a\":\"b\",\"c\":\"d\",\"list2\":[\"qwe\",\"qeqew\",\"\"],\"list3\":[{\"par1\":1,\"parf\":5.6},{\"par2\":5},{\"par3\":\"qwe\"}]},\"string\":\"Hello World\"}";
        assert(extr.pushSample(json1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);
        

        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);   

        System.out.println(schema);        
        assert(tree.get("numberTest").asText().equals("INTEGER"));  
        assert(tree.get("floatTest").asText().equals("FLOAT"));
        assert(tree.get("object").get("a").asText().equals("STRING"));
        assert(tree.get("object").get("c").asText().equals("STRING"));
        assert(tree.get("object").get("list2").iterator().next().asText().equals("STRING"));
        assert(tree.get("object").get("list3").iterator().next().get("parf").asText().equals("FLOAT"));

        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("type").asText().equals("object"));            
        assert(tree.get("properties").get("boolean").get("type").asText().equals("boolean"));
        assert(tree.get("properties").get("floatTest").get("type").asText().equals("number"));
        assert(tree.get("properties").get("object").get("type").asText().equals("object"));
        assert(tree.get("properties").get("object").get("properties").get("c").get("type").asText().equals("string"));
        assert(tree.get("properties").get("object").get("properties").get("list2").get("type").asText().equals("array"));
        assert(tree.get("properties").get("object").get("properties").get("list3").get("type").asText().equals("array"));
        assert(tree.get("properties").get("object").get("properties").get("list3").get("items").get("type").asText().equals("object"));
        assert(tree.get("properties").get("object").get("properties").get("list3").get("items").get("properties").get("parf").get("type").asText().equals("number"));
        assert(tree.get("properties").get("object").get("properties").get("list3").get("items").get("properties").get("par3").get("type").asText().equals("string"));
    }

    @Test     
    public void jsonTest8() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/json"); 
        String json1 = "{\"arrayW1\":[1,2,[\"qweqe\",\"qeqweq\",\"eqeqwe\"],[\"qweqe\",\"rftertert\"],[1,2,3,4]]}";
        assert(extr.pushSample(json1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);
       
        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);   

        System.out.println(schema);        
        var iter = tree.get("arrayW1").iterator();        
        assert(iter.next().asText().equals("INTEGER"));
        var iter2 =iter.next().iterator();
        assert(iter2.next().asText().equals("STRING"));
        assert(iter2.next().asText().equals("INTEGER"));

        assertThrowsExactly(IncompatibleWithOpenApiSchema.class, () -> extr.result().getOpenApiCompatibleSchema());     
    }        

    @Test     
    public void yamlTest1() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/yaml"); 
        String yaml1 = 
            "xx: 6";
        assert(extr.pushSample(yaml1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String yaml2 = 
            "yy: qwerty";
        assert(extr.pushSample(yaml2.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS); 
        String yaml3 = 
            "xx: 90\n"
            +"yy: qw222erty\n"
            +"aa:\n"
            +"  lol5: true\n";
        assert(extr.pushSample(yaml3.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);          
               

        var schema = extr.result().getShortStringDescription();  
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);

        assert(tree.get("xx").asText().equals("INTEGER"));
        assert(tree.get("aa").get("lol5").asText().equals("BOOLEAN"));
        assert(tree.get("yy").asText().equals("STRING"));

        System.out.println(schema);

        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("type").asText().equals("object"));            
        assert(tree.get("properties").get("yy").get("type").asText().equals("string"));        
        assert(tree.get("properties").get("aa").get("type").asText().equals("object"));        
    }    

    @Test     
    public void yamlTest2() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/yaml"); 
        String yaml1 = 
             "xx:\n"
            +"  - 6\n"
            +"  - 90";
        assert(extr.pushSample(yaml1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);         

        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);   

        System.out.println(schema);
        var iter = tree.get("xx").iterator();
        assert(iter.next().asText().equals("INTEGER"));     
        assert(!iter.hasNext());        

        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("type").asText().equals("object"));          
        assert(tree.get("properties").get("xx").get("type").asText().equals("array"));    
        assert(tree.get("properties").get("xx").get("items").get("type").asText().equals("integer"));    
    }    
    
    @Test     
    public void yamlTest3() throws SEBaseException, JsonMappingException, JsonProcessingException { 
        var extr = ExtrapolatorMaker.make("application/yaml"); 
        String yaml1 =              
             "- 6\n"
            +"- 90\n"
            +"- 9033";
        assert(extr.pushSample(yaml1.getBytes()) == Extrapolator.SampleParsingResult.SUCCESS);         

        var schema = extr.result().getShortStringDescription();        
        ObjectMapper om = new ObjectMapper(new YAMLFactory());
        var tree = om.readTree(schema);   

        System.out.println(schema);
        var iter = tree.iterator();
        assert(iter.next().asText().equals("INTEGER"));     
        assert(!iter.hasNext());    
        

        var json_str = makeJsonStr(extr.result().getOpenApiCompatibleSchema());
        System.out.println("JSON:");
        System.out.println(json_str);

        var omj = new ObjectMapper();        
        tree = omj.readTree(json_str);
        assert(tree.get("type").asText().equals("array"));          
        assert(tree.get("items").get("type").asText().equals("integer"));
    }
       
}

